# Generated by Django 3.2.9 on 2021-11-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableId', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('isOutdoor', models.BooleanField()),
                ('isBooth', models.BooleanField()),
                ('isCurAvailable', models.BooleanField()),
            ],
        ),
    ]
