# Generated by Django 3.2.9 on 2021-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='isBooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='isCurAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='isOutdoor',
            field=models.BooleanField(default=False),
        ),
    ]
