# Generated by Django 3.2.9 on 2021-11-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_reservation_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='come',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='out',
            field=models.DateTimeField(null=True),
        ),
    ]
