# Generated by Django 3.2.9 on 2021-11-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20211127_0949'),
        ('reserve', '0005_auto_20211129_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table2nd_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table2nd_id', to='table.table'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_id', to='table.table'),
        ),
    ]
