# Generated by Django 3.2.9 on 2021-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_auto_20211129_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighTrafficDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
