# Generated by Django 3.2.8 on 2021-12-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_reservation_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='is_active',
            new_name='is_expired',
        ),
        migrations.AddField(
            model_name='reservation',
            name='has_come',
            field=models.BooleanField(default=False),
        ),
    ]
