# Generated by Django 3.2.9 on 2021-12-03 16:57

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0004_auto_20211201_1008'),
        ('table', '0002_auto_20211127_0949'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('points', models.IntegerField(null=True)),
                ('prefer_payment', models.CharField(max_length=100, null=True)),
                ('isSame', models.BooleanField(default=False)),
                ('billing_addresss', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_addresss', to='address.address')),
                ('mailing_addresss', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_addresss', to='address.address')),
                ('prefer_table', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.table')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
